Repository rack/rack, pull requests merged in 2022-04, with the labels that each got.

#1861 Rework `Rack::Response#initialize` documentation to be RDoc format.
  lib/rack/response.rb
Labels: Documentation

#1864 Ensure Rack::QueryParser::ParamsTooDeepError is inherited from RangeError.
  test/spec_utils.rb
Labels: Backport

#1873 Add new query parser exception to Utils.
  lib/rack/utils.rb
Labels: Maintenance, Backport

#1872 Remove `Rack::Multipart` dependency on `Rack::Request`.
  lib/rack/multipart.rb
  lib/rack/multipart/generator.rb
  test/spec_multipart.rb
  test/spec_request.rb
Labels: Maintenance

#1846 Don't overwrite other cookie attributes when building deletion cookie.
  lib/rack/utils.rb
  test/spec_utils.rb
Labels: Needs Feedback
